services:
  chapter4-app:
    build:
      context: .        # use current directory (where Dockerfile is)
    ports:
      - "3000:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60

