services:
  chapter4-app:
    image: nour333/chapter4-express-app:latest
    ports:
      - "3000:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
